### ISSUE TITLE
Error RetrofitInstance : No Retrofit annotation found. (parameter #3)

### ISSUE THREAD

**Issue by maulana-reza** [utsmannn/simple-location-picker#1]
```
2020-09-09 07:26:17.504 29565-29624 W/System.err: java.lang.IllegalArgumentException: No Retrofit annotation found. (parameter #3)
2020-09-09 07:26:17.504 29565-29624 W/System.err:     for method RetrofitInstance.getLocation
2020-09-09 07:26:17.505 29565-29624 W/System.err:     at retrofit2.Utils.methodError(Utils.java:52)
2020-09-09 07:26:17.505 29565-29624 W/System.err:     at retrofit2.Utils.methodError(Utils.java:42)
2020-09-09 07:26:17.505 29565-29624 W/System.err:     at retrofit2.Utils.parameterError(Utils.java:61)
2020-09-09 07:26:17.505 29565-29624 W/System.err:     at retrofit2.RequestFactory$Builder.parseParameter(RequestFactory.java:311)
2020-09-09 07:26:17.505 29565-29624 W/System.err:     at retrofit2.RequestFactory$Builder.build(RequestFactory.java:182)
2020-09-09 07:26:17.505 29565-29624 W/System.err:     at retrofit2.RequestFactory.parseAnnotations(RequestFactory.java:65)
2020-09-09 07:26:17.505 29565-29624 W/System.err:     at retrofit2.ServiceMethod.parseAnnotations(ServiceMethod.java:25)
2020-09-09 07:26:17.505 29565-29624 W/System.err:     at retrofit2.Retrofit.loadServiceMethod(Retrofit.java:168)
2020-09-09 07:26:17.505 29565-29624 W/System.err:     at retrofit2.Retrofit$1.invoke(Retrofit.java:147)
2020-09-09 07:26:17.505 29565-29624 W/System.err:     at java.lang.reflect.Proxy.invoke(Proxy.java:813)
2020-09-09 07:26:17.505 29565-29624 W/System.err:     at $Proxy3.getLocation(Unknown Source)
2020-09-09 07:26:17.505 29565-29624 W/System.err:     at com.safwah.iwarga.ui.profile.map.MapsFragment$getLocation$1.invokeSuspend(MapsFragment.kt:127)
2020-09-09 07:26:17.505 29565-29624 W/System.err:     at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2020-09-09 07:26:17.505 29565-29624 W/System.err:     at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:236)
2020-09-09 07:26:17.505 29565-29624 W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
2020-09-09 07:26:17.506 29565-29624 W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
2020-09-09 07:26:17.506 29565-29624 W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
```

Code 
```kotlin

    @GET("/v1/revgeocode")
    suspend fun getLocation(
        @Query("at") at: String,
        @Query("apiKey") apiKey: String
    ): Call<Places>

    companion object {
        fun create(): RetrofitInstance {
            val logging = HttpLoggingInterceptor()
            logging.level = HttpLoggingInterceptor.Level.BODY

            val client = OkHttpClient.Builder()
                .addInterceptor(logging)
                .build()

            val retrofit = Retrofit.Builder()
                .baseUrl(BASE_URL_MAP)
                .addConverterFactory(GsonConverterFactory.create())
                .client(client)
                .build()
            return retrofit.create(RetrofitInstance::class.java)
        }
    }
```

**Comment by maulana-reza** [comment]
has been fix,
i use enqueue call back

```kotlin
val places  = retrofitInstance.getLocation(at).enqueue(object : retrofit2.Callback<Placess>{
                        override fun onResponse(call: Call<Placess>, response: Response<Placess>) {
                            v.progress_circular.visibility = View.GONE
                            done.invoke(response.body()!!.items.first())
                            if (!response.isSuccessful){
                                (context as HomeActivity).snackBar(response.errorBody().toString())
                            }
                        }
                        override fun onFailure(call: Call<Placess>, t: Throwable) {
                            (context as HomeActivity).snackBar(t.message.toString())
                        }
                    })
```
